### PR TITLE
Support for getting twitter username from twitter card metadata

### PR DESCRIPTION
**Pull request by ThomasArdal**

### CODE REVIEW

**Comment by ThomasArdal** [comment]
When thinking about this PR, I might even want to turn the code around. If there's a meta element with twitter:creator in it, we know that the handle in the value is always the creator. So, looking at the rest of the document could maybe be skipped. What do you think?

**Comment by jakubgarfield** [comment]
Thank you for your PR. I think the other way around makes more sense. 👍

**Comment by ThomasArdal** [comment]
Fixed

**Comment by jakubgarfield** [comment]
🙏

**Comment by jakubgarfield** [comment]
I'm surprised anyone else is using the extension 😄

**Comment by ThomasArdal** [comment]
@jakubgarfield I'm using it when I share some blog posts I find. To easily include the handle of the person writing the post. I also tried the Twitter Account Detector extension which is fine. But the copy feature in your extension is awesome. Would be nice to include a small copy icon next to each handle in the popup as well. I know that the first result is automatically copied, but sometimes the right one is the second result.

**Pull request merged**
